[package]
name = "archive-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
datafusion = "34.0.0"
duckdb = { version = "0.9.2", features = ["bundled", "parquet"] }
itertools = "0.12.0"
lazy_static = "1.4.0"
regex = "1.10.2"
