[package]
name = "archive-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
async-stream = "0.3.5"
axum = "0.7.4"
base64 = "0.21.7"
clap = { version = "4.4.18", features = ["derive", "env"] }
datafusion = "34.0.0"
futures = "0.3.30"
glob = "0.3.1"
itertools = "0.12.0"
lazy_static = "1.4.0"
opentelemetry = "0.21.0"
opentelemetry-jaeger = "0.20.0"
regex = "1.10.2"
reqwest = { version = "0.11.24", features = ["json"] }
rust-s3 = "0.33.0"
sentry = { version = "0.32.2", features = ["tracing"] }
serde = "1.0.195"
serde-rename-rule = "0.2.2"
serde_json = { version = "1.0.111", features = ["preserve_order"] }
subsquid-messages = { git = "https://github.com/subsquid/archive-router.git", version = "0.1.0" }
tokio = { version = "1.35.1", features = ["full", "tracing"] }
tokio-stream = "0.1.14"
tokio-util = "0.7.10"
tower-http = { version = "0.5.1", features = ["catch-panic"] }
tracing = { version = "0.1.40", features = ["async-await"] }
tracing-opentelemetry = "0.22.0"
tracing-subscriber = "0.3.18"
