[package]
name = "archive-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
async-stream = "0.3.5"
futures = "0.3.30"
itertools = "0.12.0"
lazy_static = "1.4.0"
opentelemetry = "0.21.0"
opentelemetry-jaeger = "0.20.0"
regex = "1.10.2"
rust-s3 = "0.33.0"
tokio = { version = "1.35.1", features = ["full", "tracing"] }
tokio-stream = "0.1.14"
tokio-util = "0.7.10"
tracing = { version = "0.1.40", features = ["async-await"] }
tracing-opentelemetry = "0.22.0"
tracing-subscriber = "0.3.18"
