name: docker
on:
  workflow_dispatch: # manually run
    inputs:
      tag:
        description: image tag
        required: true

env:
  CI: true

jobs:
  publish:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: subsquid-public
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: worker-rust
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Get version
        run: echo "WORKER_VERSION=$(docker run --rm worker-rust --version | cut -d ' ' -f2)" >> $GITHUB_ENV

      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          push: true
          tags: |
            subsquid/p2p-worker:${{ env.WORKER_VERSION }}
            subsquid/p2p-worker:${{ inputs.tag }}
            eu.gcr.io/subsquid-public/p2p-worker:${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
