name: docker
on:
  workflow_dispatch: # manually run
    inputs:
      tag:
        description: image tag
        required: true

env:
  CI: true

jobs:
  publish:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: Load ssh key to fetch private dependencies
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.NETWORK_SSH_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: worker-rust
          cache-from: type=gha
          cache-to: type=gha,mode=max
          ssh: default=${{ env.SSH_AUTH_SOCK }}

      - name: Get version
        run: echo "WORKER_VERSION=$(docker run --rm worker-rust --version | cut -d ' ' -f2)" >> $GITHUB_ENV

      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          push: true
          tags: |
            ghcr.io/subsquid/worker-rs:${{ env.WORKER_VERSION }}
            ghcr.io/subsquid/worker-rs:${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          ssh: default=${{ env.SSH_AUTH_SOCK }}
